### ISSUE TITLE
Some colors have bad contrast

### ISSUE THREAD

**Issue by poperigby** [dracula/qt5#1]
Not sure if this is supposed to look like this, but the purple text and blue highlight can create some bad contrast, and I don't think this blue color is part of the Dracula palette.
![Swappshot Tue Jan 12 17:02:45 2021](https://user-images.githubusercontent.com/20866468/104392986-2e479d80-54f8-11eb-8ab4-ea5dc83b30d5.png)

**Comment by TechieAndroid** [comment]
That's odd. Are you using my latest version?

I only used the light blue for links. And yes it is part of the pallette. Every color I set I got directly from the main github.

I do have a few little bugs to work out but I don't recognize this one. It was difficult making the theme because there's few clear connections between the colors set in qt5ct, e.g. I had to set and test colors several times to see what I was affecting until I got it right.

Anyways, keep me updated and I'll fix it as soon as I can.

**Comment by poperigby** [comment]
I figured out that it only has these contrast issues with Breeze. Fusion looks fine.

**Comment by TechieAndroid** [comment]
That's sounds more like GTK territory than a Qt5 problem.

I haven't done anything with GTK for a while so I'll have to look into that when I have some time, but it's probably not that Qt's theme at fault.
