### ISSUE TITLE
Incomplete instructions on draculatheme.com

### ISSUE THREAD

**Issue by ElnuDev** [dracula/qt5#3]
The instructions provided on [draculatheme.com](https://draculatheme.com) are incomplete, at least for my system running Ubuntu 21.04. In `qt5ct` I got the error "The **QT_QPA_PLATFORMTHEME** environment variable is not set (required value: **qt5ct**)" and after a quick search, I found [this thread](https://bbs.archlinux.org/viewtopic.php?id=259721) on the Arch Linux Forums with a solution: one has to edit `~/.profile` and add the line `export QT_QPA_PLATFORMTHEME="qt5ct"`, log out, and log back in again. I'm not sure of this is the right repository to open an issue on, but others might find this helpful when trying to install the Dracula qt5 theme.

**Comment by TechieAndroid** [comment]
Usually, you'd run into this problem on non-qt5 ready environments (unless I'm remembering wrong). Or custom built ones, which in that case they will know what they're doing anyway.

I don't really see the need to add this to the steps to set up the theme since it is basically a prerequisite to doing anything with qt, plus qt5ct will already tell you to add the variable. I feel like it could become too broad of a subject to have to detail in the guide.

Closing for now.

**Comment by ryleu** [comment]
As someone with a custom built setup, I have no idea what I'm doing and this got me to the right answer. Would love to get this added to instructions!
